name: velocimax2000
description: "App de velocimetro y odometro"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter_launcher_icons:
  android: "launcher_icon"   
  ios: true                   
  image_path: "assets/icon/icon.png"  
  min_sdk_android: 21    

flutter:
  uses-material-design: true
